baseURL: "https://hyoban.github.io"
title: Hyoban
theme: cayman-hugo

# Syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments

markup:
  goldmark:
    renderer:
      # parse html tags in markdown
      # https://stackoverflow.com/questions/60329235
      unsafe: true

params:
  project_name: Hyoban's blog
  project_tagline: Everything has to be studied before you can understand it.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Github Pages](https://pages.github.com/).
  cusdis_id: 4eab0f57-ebdc-4f97-9701-66535c7742fc

menu:
  nav:
    - name: Note
      url: https://github.com/hyoban/hyoban.github.io/issues
      weight: 1
    - name: Onedrive
      url: https://raspy-band-5515.hyoban.workers.dev
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3
