site_name: Hyoban 的笔记

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.sections

markdown_extensions:
  # markdown highlight
  - pymdownx.highlight
  - pymdownx.superfences
  # add HTML attributes and CSS classes to Markdown elements
  - attr_list
  # 修改 toc 链接为具体标题
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
  # 提供下划线，删除线的支持
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - 主页: index.md
  - 大数据:
    - Hadoop:
      - 安装基础环境: big-data/set-up-hadoop-on-mac.md
  - Android:
    - 准备:
      - 如何开始写一个 android 项目: android/prepare/start-writing-an-android-project.md
    - Intent:
      - Activity Result: android/intent/activity-result.md
      - 常用的 Intent: android/intent/common-intents.md
    - 数据和文件存储:
      - 文档和其它文件: android/data-storage/storage-access-framework.md
      - URI和文件操作: android/data-storage/use-uri-to-operate-file.md
